\set ON_ERROR_STOP on

-- 1. Create Configuration Table
CREATE TABLE IF NOT EXISTS configuration (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp DEFAULT now(),
    key text UNIQUE NOT NULL,
    value text NOT NULL,
    description text
);

-- Insert VAT 7.00%
INSERT INTO configuration (key, value, description) 
VALUES ('vat_percent', '7.00', 'Default VAT percentage for invoices')
ON CONFLICT (key) DO NOTHING;

-- 2. Alter invoice_line_item table
ALTER TABLE invoice_line_item 
ADD COLUMN IF NOT EXISTS line_discount_percent numeric(12,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS line_discount_amount numeric(12,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS line_net_price numeric(12,2) DEFAULT 0.00;

-- 3. Alter invoice table
ALTER TABLE invoice 
ADD COLUMN IF NOT EXISTS total_discount numeric(12,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS net_price numeric(12,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS vat_rate numeric(12,4) DEFAULT 0.0700;

ALTER TABLE invoice
ADD COLUMN IF NOT EXISTS total_price numeric(12,2) DEFAULT 0.00;

-- Update existing data to avoid nulls if any
UPDATE invoice SET total_price = total_amount WHERE total_price = 0;
UPDATE invoice SET net_price = total_amount WHERE net_price = 0;
