\set ON_ERROR_STOP on

-- Individual Lab 04: Receipt module.
-- Receipts record customer payments against one or more unpaid invoices.

CREATE TABLE IF NOT EXISTS receipt (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp DEFAULT now(),
  receipt_no text UNIQUE NOT NULL,
  receipt_date date NOT NULL,
  customer_id bigint NOT NULL REFERENCES customer(id) ON DELETE restrict ON UPDATE cascade,
  total_invoice_amount_due numeric(12,2) DEFAULT 0,
  total_amount_received numeric(12,2) DEFAULT 0,
  total_amount_still_remaining numeric(12,2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS receipt_line_item (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp DEFAULT now(),
  receipt_id bigint NOT NULL REFERENCES receipt(id) ON DELETE cascade ON UPDATE cascade,
  invoice_id bigint NOT NULL REFERENCES invoice(id) ON DELETE restrict ON UPDATE cascade,
  invoice_amount_due numeric(12,2) DEFAULT 0,
  receipt_amount numeric(12,2) DEFAULT 0,
  invoice_amount_still_remaining numeric(12,2) DEFAULT 0,
  UNIQUE (receipt_id, invoice_id)
);

CREATE INDEX IF NOT EXISTS idx_receipt_date ON receipt(receipt_date);
CREATE INDEX IF NOT EXISTS idx_receipt_customer ON receipt(customer_id);
CREATE INDEX IF NOT EXISTS idx_receipt_line_receipt ON receipt_line_item(receipt_id);
CREATE INDEX IF NOT EXISTS idx_receipt_line_invoice ON receipt_line_item(invoice_id);

